In [1]:
import numpy as np
from numpy import genfromtxt

In [2]:
data = genfromtxt('../DATA/bank_note_data.txt', delimiter=',')

In [3]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [4]:
labels = data[:,-1]

In [5]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [6]:
features = data[:,0:-1]

In [7]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [8]:
X = features
y = labels

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [11]:
len(X_train)

960

In [12]:
len(X)

1372

In [13]:
from sklearn.preprocessing import MinMaxScaler

In [14]:
scaler = MinMaxScaler()

In [15]:
X_train_scaled = scaler.fit_transform(X_train)

In [16]:
X_test_scaled = scaler.fit_transform(X_test)

In [17]:
X_train_scaled.max()

1.0000000000000002

In [20]:
from keras.models import Sequential
from keras.layers import Dense

In [21]:
model = Sequential()

model.add(Dense(4, activation='relu'))

model.add(Dense(8,activation='relu'))

model.add(Dense(1,activation='sigmoid'))

2024-09-06 13:05:51.871600: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-09-06 13:05:51.871796: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1960] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


In [22]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [23]:
model.fit(X_train_scaled, y_train, epochs=50, verbose=2)

Epoch 1/50
30/30 - 0s - loss: 0.6809 - accuracy: 0.5552 - 302ms/epoch - 10ms/step
Epoch 2/50
30/30 - 0s - loss: 0.6779 - accuracy: 0.5552 - 26ms/epoch - 856us/step
Epoch 3/50
30/30 - 0s - loss: 0.6748 - accuracy: 0.5552 - 24ms/epoch - 803us/step
Epoch 4/50
30/30 - 0s - loss: 0.6715 - accuracy: 0.5552 - 18ms/epoch - 594us/step
Epoch 5/50
30/30 - 0s - loss: 0.6677 - accuracy: 0.5552 - 18ms/epoch - 599us/step
Epoch 6/50
30/30 - 0s - loss: 0.6632 - accuracy: 0.5552 - 19ms/epoch - 627us/step
Epoch 7/50
30/30 - 0s - loss: 0.6578 - accuracy: 0.5552 - 19ms/epoch - 617us/step
Epoch 8/50
30/30 - 0s - loss: 0.6510 - accuracy: 0.5583 - 18ms/epoch - 594us/step
Epoch 9/50
30/30 - 0s - loss: 0.6409 - accuracy: 0.5740 - 23ms/epoch - 769us/step
Epoch 10/50
30/30 - 0s - loss: 0.6304 - accuracy: 0.6062 - 22ms/epoch - 735us/step
Epoch 11/50
30/30 - 0s - loss: 0.6178 - accuracy: 0.6583 - 21ms/epoch - 690us/step
Epoch 12/50
30/30 - 0s - loss: 0.5978 - accuracy: 0.6833 - 21ms/epoch - 714us/step
Epoch 13/50
3

In [39]:
# score = model.evaluate(X_train_scaled, X_test_scaled)

In [27]:
from sklearn.metrics import confusion_matrix, classification_report